# Generated by Django 5.0.1 on 2024-01-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_flashcarddesafio_desafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
